from core.utils import Dict

WORLD_TILE_SIZE = 64

WORLD_BOUNDS = Dict()
WORLD_BOUNDS.LEFT = 0
WORLD_BOUNDS.RIGHT = WORLD_TILE_SIZE * 30
WORLD_BOUNDS.TOP = 0
WORLD_BOUNDS.BOTTOM = WORLD_TILE_SIZE * 20
